enfants_index:
    path:     /
    defaults: { _controller: "EnfantsBundle:Enfants:index" }
    methods:  GET

enfants_show:
    path:     /{id}/show
    defaults: { _controller: "EnfantsBundle:Enfants:show" }
    methods:  GET

enfants_new:
    path:     /new
    defaults: { _controller: "EnfantsBundle:Enfants:new" }
    methods:  [GET, POST]

enfants_edit:
    path:     /{id}/edit
    defaults: { _controller: "EnfantsBundle:Enfants:edit" }
    methods:  [GET, POST]

enfants_delete:
    path:     /{id}/delete
    defaults: { _controller: "EnfantsBundle:Enfants:delete" }
    methods:  DELETE
